name: Marketplace Action Demo

on: [push, pull_request, workflow_dispatch]

jobs:
  apptainer:
    runs-on: ubuntu-22.04

    env:
      APPTAINER_VERSION: "1.3.6"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Restore cached .sif image
        id: cache-sif
        uses: actions/cache@v4
        with:
          path: demo.sif
          key: sif-${{ runner.os }}-${{ env.APPTAINER_VERSION }}-${{ hashFiles('container.def', 'install_boost_openssl.sh', '*.deb') }}
          restore-keys: |
            sif-${{ runner.os }}-

      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: ${{ env.APPTAINER_VERSION }}

      - name: Verify definition file
        run: |
          if [ ! -f container.def ]; then
            echo "container.def not found"
            exit 1
          fi
          echo "Using:"
          realpath container.def

      - name: Build container (if no cache hit)
        if: ${{ steps.cache-sif.outputs.cache-hit != 'true' }}
        run: |
          echo "Cache miss — building demo.sif..."
          apptainer build demo.sif container.def

      - name: Use cached container
        if: ${{ steps.cache-sif.outputs.cache-hit == 'true' }}
        run: |
          echo "Cache hit — using existing demo.sif"
          ls -lh demo.sif

      - name: Save .sif image to cache
        if: ${{ steps.cache-sif.outputs.cache-hit != 'true' }}
        uses: actions/cache@v4
        with:
          path: demo.sif
          key: sif-${{ runner.os }}-${{ env.APPTAINER_VERSION }}-${{ hashFiles('container.def', 'install_boost_openssl.sh', '*.deb') }}

      - name: Run inside container
        run: |
          apptainer exec demo.sif bash -c "echo Hello from inside; ls -lh /"