name: Marketplace Action Demo

on:
  workflow_dispatch:
    inputs:
      build_from_scratch:
        description: "Build new .sif from .def?"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  apptainer:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - name: Verify build dependencies
        run: |
          for f in install_boost_openssl.sh openssl-package.deb boost-package.deb; do
            if [ ! -f "$f" ]; then
              echo "Missing dependency: $f"
              exit 1
            fi
          done
          echo "All dependency files are present."

      - name: Upload build dependency artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apptainer-build-deps
          path: |
            install_boost_openssl.sh
            openssl-package.deb
            boost-package.deb

      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: "1.3.6"

      - name: Verify definition file
        run: |
          if [ ! -f container.def ]; then
            echo "container.def not found"
            exit 1
          fi
          echo "Using definition:"
          realpath container.def

      - name: Build container
        if: ${{ inputs.build_from_scratch == 'true' }}
        run: |
          apptainer build demo.sif container.def

      - name: Use existing container
        if: ${{ inputs.build_from_scratch == 'false' }}
        run: |
          if [ ! -f demo.sif ]; then
            echo "demo.sif not found"
            exit 1
          fi

      - name: Run inside container
        run: |
          apptainer exec demo.sif bash -c "echo Hello from inside; ls -lh /"