# Copyright © 2019-2023
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Mainline Vortex

# on: [push, pull_request]

on:
  # can ignore unless debugging
  workflow_dispatch:
    inputs:
      build_from_scratch:
        description: "Build new .sif from .def?"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  setup:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Toolchain Directory
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: tools
          key: ${{ matrix.os }}-toolchain-v0.1
          restore-keys: |
            ${{ matrix.os }}-toolchain-

      - name: Cache Third Party Directory
        id: cache-thirdparty
        uses: actions/cache@v4
        with:
          path: third_party
          key: ${{ matrix.os }}-thirdparty-v0.1
          restore-keys: |
            ${{ matrix.os }}-thirdparty-

      - name: Setup Toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: |
          TOOLDIR=$PWD/tools
          mkdir -p build
          cd build
          ../configure --tooldir=$TOOLDIR
          ci/toolchain_install.sh --all

      - name: Setup Third Party
        if: steps.cache-thirdparty.outputs.cache-hit != 'true'
        run: |
          make -C third_party > /dev/null

  build:
    needs: setup
    strategy:
      matrix:
        os: [ubuntu-22.04]
        xlen: [32]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo bash ./ci/install_dependencies.sh

      - name: Cache Toolchain Directory
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: tools
          key: ${{ matrix.os }}-toolchain-v0.1
          restore-keys: |
            ${{ matrix.os }}-toolchain-

      - name: Cache Third Party Directory
        id: cache-thirdparty
        uses: actions/cache@v4
        with:
          path: third_party
          key: ${{ matrix.os }}-thirdparty-v0.1
          restore-keys: |
            ${{ matrix.os }}-thirdparty-

      - name: Run Build
        run: |
          TOOLDIR=$PWD/tools
          mkdir -p build${{ matrix.xlen }}
          cd build${{ matrix.xlen }}
          ../configure --tooldir=$TOOLDIR --xlen=${{ matrix.xlen }}
          source ci/toolchain_env.sh
          make software -s > /dev/null
          make tests -s > /dev/null

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ matrix.xlen }}
          path: build${{ matrix.xlen }}

  tests:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        name: [kernel]
        xlen: [32]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo bash ./ci/install_dependencies.sh

      - name: Cache Toolchain Directory
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: tools
          key: ${{ matrix.os }}-toolchain-v0.1
          restore-keys: |
            ${{ matrix.os }}-toolchain-

      - name: Cache Third Party Directory
        id: cache-thirdparty
        uses: actions/cache@v4
        with:
          path: third_party
          key: ${{ matrix.os }}-thirdparty-v0.1
          restore-keys: |
            ${{ matrix.os }}-thirdparty-

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ matrix.xlen }}
          path: build${{ matrix.xlen }}

      - name: Run tests
        run: |
          cd build${{ matrix.xlen }}
          source ci/toolchain_env.sh
          chmod -R +x . # Ensure all files have executable permissions
          if [ "${{ matrix.name }}" == "regression" ]; then
            ./ci/regression.sh --unittest
            ./ci/regression.sh --isa
            ./ci/regression.sh --kernel
            ./ci/regression.sh --regression
          else
            ./ci/regression.sh --${{ matrix.name }}
          fi

  complete:
    runs-on: ubuntu-22.04
    needs: tests

    steps:
      - name: Check Completion
        run: echo "All matrix jobs passed"