name: Custom Apptainer Action Demo

on:
  # can ignore unless debugging
  workflow_dispatch:
    inputs:
      build_from_scratch:
        description: "Build new .sif from .def?"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  apptainer:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer squashfs-tools

      - name: Verify definition file
        run: |
          if [ ! -f container.def ]; then
            echo "container.def not found"
            exit 1
          fi
          echo "Using:"
          realpath container.def

      - name: Build container
        # actions will open your repo from its root
        # this means the top-level directory of the repo after actions/checkout (above) runs
        # with this in mind, set your .def / .sif paths accordingly
        if: ${{ inputs.build_from_scratch == 'true' }}
        run: |
          apptainer build demo.sif container.def

      - name: Use existing container
        if: ${{ inputs.build_from_scratch == 'false' }}
        run: |
          if [ ! -f demo.sif ]; then
            echo "demo.sif not found"
            exit 1
          fi

      - name: Run inside container
        run: |
          apptainer exec demo.sif bash -c "echo Hello from inside; ls -lh /"