name: Apptainer CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        xlen: [32]
        name: [kernel]
    runs-on: ${{ matrix.os }}

    env:
      APPTAINER_VERSION: "1.4.3"
      TOOLDIR: ${{ github.workspace }}/tools

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Check .sif Cache
        id: cache-sif
        uses: actions/cache@v4
        with:
          path: miscs/apptainer/vortex.sif
          key: vortex-sif-${{ matrix.os }}-${{ env.APPTAINER_VERSION }}-${{ hashFiles('miscs/apptainer/vortex.def', 'miscs/apptainer/install_boost_openssl.sh', 'miscs/apptainer/*.deb') }}
          restore-keys: |
            sif-${{ matrix.os }}-

      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: ${{ env.APPTAINER_VERSION }}

      - name: Build Container On Miss
        if: ${{ steps.cache-sif.outputs.cache-hit != 'true' }}
        run: |
          rm -f miscs/apptainer/vortex.sif
          pushd miscs/apptainer
          apptainer build vortex.sif vortex.def
          popd

      - name: Save .sif to Cache
        if: ${{ steps.cache-sif.outputs.cache-hit != 'true' }}
        uses: actions/cache@v4
        with:
          path: miscs/apptainer/vortex.sif
          key: vortex-sif-${{ matrix.os }}-${{ env.APPTAINER_VERSION }}-${{ hashFiles('miscs/apptainer/vortex.def', 'miscs/apptainer/install_boost_openssl.sh', 'miscs/apptainer/*.deb') }}

      - name: Upload .sif as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sif-${{ matrix.os }}
          path: miscs/apptainer/vortex.sif

      - name: Access Toolchain Cache
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: tools
          key: toolchain-${{ matrix.os }}-${{ hashFiles('ci/toolchain_install.sh') }}
          restore-keys: |
            toolchain-${{ matrix.os }}-

      - name: Build Toolchain On Miss
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss: building toolchain..."
          TOOLDIR=$PWD/tools
          mkdir -p build
          cd build
          ../configure --tooldir=$TOOLDIR
          ci/toolchain_install.sh --all

      - name: Save Updated Toolchain Cache
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: tools
          key: toolchain-${{ matrix.os }}-${{ hashFiles('ci/toolchain_install.sh') }}
      
      - name: Access Third Party Cache
        id: cache-thirdparty
        uses: actions/cache@v4
        with:
          path: third_party
          key: ${{ matrix.os }}-thirdparty-v0.1
          restore-keys: |
            ${{ matrix.os }}-thirdparty-

      - name: Build Third Party On Miss
        if: steps.cache-thirdparty.outputs.cache-hit != 'true'
        run: |
          make -C third_party > /dev/null

      - name: Save Updated Third Party Cache
        if: steps.cache-thirdparty.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: third_party
          key: ${{ matrix.os }}-thirdparty-v0.1
      
      - name: Run Build In Apptainer
        run: |
          apptainer exec \
            --bind ${{ github.workspace }}:${{ github.workspace }} \
            --bind ${{ github.workspace }}/tools:/tools \
            --bind ${{ github.workspace }}/third_party:${{ github.workspace }}/third_party \
            --pwd ${{ github.workspace }} \
            --env TOOLDIR=/tools \
            miscs/apptainer/vortex.sif bash <<'EOF'
              set -e
              echo "--- Inside Container ---"
              
              echo "--- Configure Root and CI folder ---"
              ./configure --tooldir=$TOOLDIR --xlen=${{ matrix.xlen }}

              mkdir -p build${{ matrix.xlen }}
              pushd build${{ matrix.xlen }}

              echo "--- Configure Build Folder ---"
              ../configure --tooldir=$TOOLDIR --xlen=${{ matrix.xlen }}

              echo "--- Source Toolchain ---"
              source ../ci/toolchain_env.sh

              echo "--- Starting build ---"
              make software -s
              make tests -s
              popd
          EOF

      # - name: Run tests in Apptainer
      #   run: |
      #     pushd build${{ matrix.xlen }}
      #     source ci/toolchain_env.sh
      #     chmod -R +x . # Ensure all files have executable permissions
      #     if [ "${{ matrix.name }}" == "regression" ]; then
      #       ./ci/regression.sh --unittest
      #       ./ci/regression.sh --isa
      #       ./ci/regression.sh --kernel
      #       ./ci/regression.sh --regression
      #     else
      #       ./ci/regression.sh --${{ matrix.name }}
      #     fi
      #     popd

  complete:
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
      - name: Check Completion
        run: echo "All matrix jobs passed successfully."